// Cloudflare Pages Function: /functions/sync-users.js
// Syncs the users list to GitHub's users.json using a server-side PAT secret.
// Called by the AMC Time Tracker app when a user is added/removed/updated.
// Requires GITHUB_PAT environment variable set in Cloudflare Pages settings.

export async function onRequestPost(context) {
  const { request, env } = context;

    // CORS headers
      const corsHeaders = {
          'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Methods': 'POST, OPTIONS',
                  'Access-Control-Allow-Headers': 'Content-Type',
                    };

                      try {
                          const pat = env.GITHUB_PAT;
                              if (!pat) {
                                    return new Response(JSON.stringify({ error: 'GITHUB_PAT not configured' }), {
                                            status: 500,
                                                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                          });
                                                              }

                                                                  // Parse request body
                                                                      const body = await request.json();
                                                                          const { users } = body;

                                                                              if (!users || !Array.isArray(users)) {
                                                                                    return new Response(JSON.stringify({ error: 'Invalid users data' }), {
                                                                                            status: 400,
                                                                                                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                          });
                                                                                                              }
                                                                                                              
                                                                                                                  const owner = 'amedcompliance';
                                                                                                                      const repo = 'amc-tracker';
                                                                                                                          const file = 'users.json';
                                                                                                                              const apiBase = 'https://api.github.com';
                                                                                                                              
                                                                                                                                  // Get current file SHA
                                                                                                                                      const fileResp = await fetch(`${apiBase}/repos/${owner}/${repo}/contents/${file}`, {
                                                                                                                                            headers: {
                                                                                                                                                    Authorization: `token ${pat}`,
                                                                                                                                                            Accept: 'application/vnd.github.v3+json',
                                                                                                                                                                    'User-Agent': 'AMC-Tracker-App',
                                                                                                                                                                          },
                                                                                                                                                                              });
                                                                                                                                                                              
                                                                                                                                                                                  if (!fileResp.ok) {
                                                                                                                                                                                        return new Response(JSON.stringify({ error: 'Failed to fetch current file' }), {
                                                                                                                                                                                                status: 500,
                                                                                                                                                                                                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                                                                                              });
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                  
                                                                                                                                                                                                                      const fileData = await fileResp.json();
                                                                                                                                                                                                                          const currentSha = fileData.sha;
                                                                                                                                                                                                                          
                                                                                                                                                                                                                              // Build users list - strip passwords and sensitive data
                                                                                                                                                                                                                                  const usersToSave = users
                                                                                                                                                                                                                                        .filter(u => u.role !== 'admin' && u.id !== 1)
                                                                                                                                                                                                                                              .map(u => ({
                                                                                                                                                                                                                                                      id: u.id,
                                                                                                                                                                                                                                                              name: u.name,
                                                                                                                                                                                                                                                                      email: u.email,
                                                                                                                                                                                                                                                                              role: u.role,
                                                                                                                                                                                                                                                                                      dept: u.dept,
                                                                                                                                                                                                                                                                                              shift: u.shift,
                                                                                                                                                                                                                                                                                                      jobTitle: u.jobTitle || '',
                                                                                                                                                                                                                                                                                                              phone: u.phone || '',
                                                                                                                                                                                                                                                                                                                      status: u.status,
                                                                                                                                                                                                                                                                                                                              startDate: u.startDate,
                                                                                                                                                                                                                                                                                                                                      invited: u.invited || false,
                                                                                                                                                                                                                                                                                                                                              manager: u.manager || null,
                                                                                                                                                                                                                                                                                                                                                      leaveBalance: u.leaveBalance || { vacation: 6, sick: 4, personal: 2 },
                                                                                                                                                                                                                                                                                                                                                              needsSetup: u.needsSetup !== false,
                                                                                                                                                                                                                                                                                                                                                                      color: u.color || 1,
                                                                                                                                                                                                                                                                                                                                                                              pin: u.pin || '0000',
                                                                                                                                                                                                                                                                                                                                                                                    }));
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        const content = JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                      users: usersToSave,
                                                                                                                                                                                                                                                                                                                                                                                                              updated: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                      note: 'AMC Time Tracker user database. Managed automatically by the app.',
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
                                                                                                                                                                                                                                                                                                                                                                                                                                        2
                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                // Encode to base64
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const encoded = btoa(unescape(encodeURIComponent(content)));
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Update file on GitHub
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const updateResp = await fetch(`${apiBase}/repos/${owner}/${repo}/contents/${file}`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  method: 'PUT',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Authorization: `token ${pat}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Accept: 'application/vnd.github.v3+json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'User-Agent': 'AMC-Tracker-App',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: `Update users.json (${usersToSave.length} users)`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    content: encoded,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sha: currentSha,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!updateResp.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const errText = await updateResp.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response(JSON.stringify({ error: 'GitHub update failed', details: errText }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(JSON.stringify({ ok: true, count: usersToSave.length }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return new Response(JSON.stringify({ error: err.message }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export async function onRequestOptions() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(null, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 204,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Access-Control-Allow-Origin': '*',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Access-Control-Allow-Methods': 'POST, OPTIONS',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Access-Control-Allow-Headers': 'Content-Type',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
